// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/appointments": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/appointments";
  };
  "./layouts/auth.tsx": {
    id: "layouts/auth";
    page: "/" | "/appointments";
  };
  "./layouts/dashboard.tsx": {
    id: "layouts/dashboard";
    page: "/" | "/appointments";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/appointments.tsx": {
    id: "routes/appointments";
    page: "/appointments";
  };
};